let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("dZNdj6IwFIb/SsO1RgsC3nb4GHe0K7HMjsZ4gYpAosVlOruZf7+0p0Ix2ZvT9nkP5Xx1v7cInloji7LX1voOIgmzDqO99ZJK/EJTbSULwqA9BfUXF3kTNl9Ff0LqqJxoKDHYnAtEeYGSprh9apkpmZkyO5V1fQWHSMUzm4lSLYjQGLjXxxlEEGTkSza3bRRE/UYqsfLGU0RiiAYxkV0uWsOGRpwJcTW3TT6bEF9zx+BtAABnprOt4EL99YMR+c/bGbH8pDnueEw1sgeuSf0ptOB0AssuufgGrFJdy+xnro9iKMBijgfFiiG4HxvZNm05r/9koqq5kt5oX8bVBm552xilrblospOoOLRzOe01qnNf+sZf1ysyjhlctDJmqWP24ILJAu5YGe1kOhuq5otGYbD+KTf5OdBRJ+AdMm0VS5P21FvJmKsaUImyrK9nc6vUVNacpUm3AE3giB+LpKk5bvXtBpBI195K9g6OW+lI6BZi2+KuW/EYe2h9h+Heev/hZkXjqijlk2K/z1yrdq+mY2eO0iar+KNFu2kfwWtzR+04NSAYoT0i2/nD59XxjUxql1+v9V+0qY7HtvLPZ/geP38/QmEuENavdyi3r9eUl2YmzhS3c2zKi7n7JH+YMnPNhztobey55nv/PubN+FfGzzlvd4V28UyXMrtf2yJah8M/", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [WCC = _t, Group = _t, Unit = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"WCC", type text}, {"Group", type text}, {"Unit", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Group", "Group-Work Center"}, {"Unit", "Unit-Work Center"}}),
    #"Added Conditional Column" = Table.AddColumn(#"Renamed Columns", "Group Sort", each if [#"Group-Work Center"] = "44th" then 1 else if [#"Group-Work Center"] = "MDS" then 2 else if [#"Group-Work Center"] = "MSG" then 3 else if [#"Group-Work Center"] = "MXG" then 4 else if [#"Group-Work Center"] = "OG" then 5 else if [#"Group-Work Center"] = "WSA" then 6 else if [#"Group-Work Center"] = "Yellow Ribbon" then 7 else if [#"Group-Work Center"] = "RPA-Withhold" then 8 else if [#"Group-Work Center"] = "STP1" then 9 else if [#"Group-Work Center"] = "BMT" then 9 else if [#"Group-Work Center"] = "STP2" then 10 else if [#"Group-Work Center"] = "CMD" then 11 else if [#"Group-Work Center"] = "CMS" then 12 else if [#"Group-Work Center"] = "TAP" then 13 else if [#"Group-Work Center"] = "Counter Drug" then 14 else if [#"Group-Work Center"] = "MEDCON" then 15 else if [#"Group-Work Center"] = "PTP" then 16 else if [#"Group-Work Center"] = "IRT" then 17 else if [#"Group-Work Center"] = "10 AF" then 18 else if [#"Group-Work Center"] = "822 CE" then 19 else 99),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Conditional Column",{{"Group Sort", Int64.Type}})
in
    #"Changed Type1"
